# Site settings
title: Mayank Agrawal
description: 'Developer | Open source enthusiast'
url: 'mayank-agarwal-96.github.io'
baseurl: '/mayank/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Mayank Agrawal'
  email: agarwalm214@gmail.com
  twitter_username: 
  facebook_username: 
  github_username:  mayank-agarwal-96
  linkedin_username:  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
